### ISSUE TITLE
setup git remote after create

### ISSUE THREAD

**Issue by sajmoon** [maximilianschmitt/gitclick#2]
After creating a remote repo, I would want that repo to (optionally) be set up as a git remote.

This would eliminate the need to copy/paste the url.

Example usage could be:

```
$ gitclick create
(info about what was created)
Add as remote(y/N)
remote name:
```

or using flags

```
gitclick create --set-remote="origin"
```

**Comment by maximilianschmitt** [comment]
Great idea @sajmoon, thanks! I think the --set-remote flag is probably the best option:

`gitclick create --set-remote` could set `remote origin` by default. Optionally, you could specify something like `gitclick create --set-remote=remote-name`. You're more than welcome to submit a pull request, otherwise I might implement it myself. Thanks! :)

**Comment by sajmoon** [comment]
Imagine that you code away and then you need a remote repo. So you create one. `gitclick create`. Darn. Forgot to add a remote, and you are back to copy-paste. And if your not in tmux you might have to use the mouse. 

Would it not be nice if you could `gitclick set-remote` and somehow it would knew the last repo you create and helped you fix it afterwards.

But that might be a totally different problem, with the need to store data etc. Just a though though.

**Comment by maximilianschmitt** [comment]
That's another great idea. I'm implementing your first suggestion right now. :)

**Comment by maximilianschmitt** [comment]
@sajmoon if you update gitclick by typing `npm i gitclick -g`, [you can now use the `--set-origin` option as you described](https://github.com/maximilianschmitt/gitclick/commit/7792d6b4fd6580dd789b56374d1f072b9be5e70c). :)

**Comment by sajmoon** [comment]
Sweet. Awesome! Ill check it when I get home. Good work! =)
