### ISSUE TITLE
Running any command after install

### ISSUE THREAD

**Issue by coltonfitzgerald** [maximilianschmitt/gitclick#3]
I ran "npm install gitclick -g" and any command I try and run for gitclick gives me this error:

/usr/local/lib/node_modules/gitclick/bin/gitclick:4
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by maximilianschmitt** [comment]
Hi @coltonfitzgerald! Thanks for the comment. It looks like the latest version of node.js does not support `const` yet. gitclick should work fine with io.js. Could you give that a try? I recommend checking out [n](https://github.com/tj/n) to easily install node.js and io.js.

**Comment by bradcerasani** [comment]
Seeing this too running node.js latest (v0.12.2)

While in theory there shouldn't be any conflict using io.js for day-to-day dev, not sure I want to _just_ to use this module. Until there is [reconciliation between node and io.js](http://www.infoworld.com/article/2910594/node-js/npm-founder-foresees-merger-node-js-io-js.html), you may want to consider adding support for v0.12.2 or specifying in the readme that this is currently io.js only.

**Comment by maximilianschmitt** [comment]
Good point, @bradcerasani. I've added support for node.js through babel in gitclick version `^0.2.0`. Let me know if that works!

**Comment by bradcerasani** [comment]
Hmm, still seeing the same issue with gitclick `v0.2.1` on node `v0.12.2`. Works fine on io `v1.6.4`

Demo (pardon the screenflow window): http://bpxl.io/qKvb/3OYYyeUo

**Comment by maximilianschmitt** [comment]
Hey @bradcerasani. Thanks for the update and the screencast, that made it easy to reproduce. For me it works as expected with node `v.0.12.2` when doing `npm link` but if I `npm install gitclick -g` it doesn't work either... I'll figure it out and post back here when I do. Thanks for helping out with the bug reports! :)

**Comment by maximilianschmitt** [comment]
Ok @bradcerasani I think I finally fixed it with version `0.2.2`:

![screen shot 2015-04-19 at 22 19 41](https://cloud.githubusercontent.com/assets/3694962/7221197/35f49054-e6e2-11e4-8d3a-26a1ec5fc11a.png)

If you have the time, can you check out if it works for you too? Thanks! :)

**Comment by maximilianschmitt** [comment]
nevermind... there's still an issue. I'm sorry. :D

**Comment by maximilianschmitt** [comment]
Ok, I just published `0.2.3`. I am confident that it works now. It took me quite some time to figure out the issue, but I think I got it. Let me know if you get a chance to try it out, thanks again! :)

**Comment by bradcerasani** [comment]
`0.2.3` is working for me! Thanks Max

**Comment by maximilianschmitt** [comment]
Awesome, I'm very glad to hear that. Thanks again for your help! :)
