### ISSUE TITLE
Use it with an organization namespace

### ISSUE THREAD

**Issue by agonbina** [maximilianschmitt/gitclick#6]
Hi, 

Is it possible to create a repo on a Bitbucket organization(team), instead of my Bitbucket personal account(username)?

So if my username is `agonbina` and I have a Bitbucket org `my-company`, can I create a repo within `my-company`?

**Comment by maximilianschmitt** [comment]
Hey! Teams are currently not supported by gitclick.

I checked with the Bitbucket API and it's definitely possible to add to gitclick. I just wonder what a good command/workflow for this feature would be? Maybe something like this:

```
gitclick create {repo-name} as {team-name} on {account}
```

What do you think?

**Comment by agonbina** [comment]
That looks great to me :+1:

**Comment by maximilianschmitt** [comment]
Great, thanks for the feedback. I'll see if I can get this implemented once I have some spare time. I'll keep you posted!

**Comment by maximilianschmitt** [comment]
Hey, I just had some time and went ahead and implemented it. Team support is in for GitHub and Bitbucket in gitclick `0.4.12`.

Syntax is:

```
gitclick create [<repository>] [as <organisation>] [on <account>] [options]
```

Please let me know if this works as expected for you.

**Comment by agonbina** [comment]
Cool, tried it with Bitbucket and it works :+1: 

I have a few more ideas that I would find useful personally: 
- Use [rc](https://www.npmjs.com/package/rc) so that we can set default options, I see the Bitbucket API supports the `language` option along `private, no-issues etc`. when creating a repo. We could set these options in a `gitclickrc` file so that we don't have to specify them each time within a given context :)
  For example if I am working in some modules within a team(ex. "my-team") folder, I could create the rc configuration file and this would be the default { team: "my-team", language: "Node.js", private: true } for all the repos within that folder
- Remove a repository, similar to `create`, ex: `gitclick remove [<repository>] [from <organization>] [on <account>]`

Of course that is just a suggestion :+1:

**Comment by maximilianschmitt** [comment]
Thanks for the feedback! I'd suggest you create two separate issues for the feature requests, then we could discuss them there. :)
