### ISSUE TITLE
ability to set default options using a gitclickrc file

### ISSUE THREAD

**Issue by agonbina** [maximilianschmitt/gitclick#7]
Use [rc](https://www.npmjs.com/package/rc) so that we can set default options, I see the Bitbucket API supports the `language` option along `private, no-issues etc`. when creating a repo. We could set these options in a `gitclickrc` file so that we don't have to specify them each time within a given context :)
For example if I am working in some modules within a team(ex. "my-team") folder, I could create the rc configuration file and this would be the default { team: "my-team", language: "Node.js", private: true } for all the repos within that folder

**Comment by maximilianschmitt** [comment]
I like the idea of default options. This was actually a thing in the previous version of gitclick, but the way it was implemented was pretty complicated. I think using a .gitclickrc file is a good idea. Is this what you are suggesting?

**Directory structure:**

```
projects/
  work/
    .gitclickrc
  personal/
    .gitclickrc
```

**work/.gitclickrc might have a configuration that looks like this:**

``` json
{
  "account": "bitbucket-work",
  "team": "my-company",
  "issues": true,
  "private": true,
  "wiki": false
}
```

**personal/.gitclickrc could look like this:**

``` json
{
  "account": "github",
  "issues": true,
  "private": false,
  "wiki": true,
  "language": "node.js"
}
```

If I am within a folder under `personal`, gitclick would use the `personal/.gitclickrc` as default values whenever I run a `gitclick create`.

I could also have another `.gitclickrc` in my home directory that could hold default configuration values for commands I run from other directories.

Is this kind of how you imagined it?

**Comment by agonbina** [comment]
Yep that's is exactly right. I tend to create a lot of modules when I am working on a large project, whether it is a Node.js service/server or a single page app built out of many components, so I end up manually creating a repo for each module. Locally I keep these modules/projects under the same folder so it would be nice to be able to just do `gitclick create` and have it use the default options, which can be overriden using arguments :+1:
